### ISSUE TITLE
Connect sql databases with connection strings

### ISSUE THREAD

**Issue by GrayFlash** [odpf/meteor#139]
Currrently, we expect user to pass his UserID and Password in recipe and we have static uri for using these to setup connection with database. eg: for mysql we have it as ```fmt.Sprintf("%s:%s@tcp(%s)/", config.UserID, config.Password, config.Host)```.

We also have these as mandatory values in and we return an error if they are absent. But it is possible to user a lot of db's and dashboards with default values as username and no-password at all, for eg: ```root@tcp((localhost:3306)/```. So, I think we should allow it. 

Update the extractor config to make Username and Password optional, and make the connection URI dynamic.

**Comment by GrayFlash** [comment]
@StewartJingga @ravisuhag wdyt??

**Comment by StewartJingga** [comment]
yess, we could remove username and password from config and use `ConnectionString` instead
