### ISSUE TITLE
Use emitter in extractor interface

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#158]
Instead of using a channel in the extractor interface, we can use an emitter that simplifies writing plugins for end-users and emitter takes care of streaming data to processors and sinks. 

```
emitter.Emit(interface{})
emitter.Close()
```

**Comment by StewartJingga** [comment]
@ravisuhag  we could also do it by changing our plugins interface along with emitter like this.

```
type Emitter struct {
	Emit(data interface{})
	Close()
}

type Extractor interface {
	Init(ctx context.Context, config map[string]interface{}) error
	Extract(ctx context.Context, emitter Emitter) error
}

type Processor interface {
	Init(ctx context.Context, config map[string]interface{}) error
	Process(ctx context.Context, data interface{}) (res interface{}, err error)
}

type Syncer interface {
	Init(ctx context.Context, config map[string]interface{}) error
	Sink(ctx context.Context, data interface{}) error
}
```

`Init()` will be called when setting up all the plugins for a run before actually running them.
`Extract()` will be called once on a run and receive an emitter to emit the data (abstracting channel)
`Process()` and `Sink()` will be called n times during a run where n is the number of data emitted by extractor.
Also Processor and Sink will not have any streaming context (channel or emitter) as they will be abstracted inside the runner agent.

wdyt?

**Comment by ravisuhag** [comment]
@StewartJingga What are the pros and cons we see of removing channels from the Process and Sink?
cc @kushsharma

**Comment by StewartJingga** [comment]
> @StewartJingga What are the pros and cons we see of removing channels from the Process and Sink?

Pros:
1. Processor and Sink do not need to handle process blocking (e.g. looping channel values to block) and all the hardwork will be done and managed by the agent or perhaps emitter.
2. Reduce chance of error by contributors when creating/modifying processors and sinks since we do not expect them to handle channel themselves.
3. Improve control and predictability as we control the framework/lifecycle of processors and sinks.
4. Less context is needed to contribute as we already build the lifecycle and they just need to implement the interface.

Cons:
1. May reduce flexibility, since currently everything is done in one Process function (setup, looping, etc) where it is up to the users to do whatever they want as we are just passing them configs and channels.

**Comment by ravisuhag** [comment]
@StewartJingga One thing we need to see is how batching will work? For some sinks, we would not want to send data one message at a time e.g. Kafka. Where users would want to create a batch of events before flushing it.

**Comment by kushsharma** [comment]
The message interface will also help me get rid of our current reflection pointer hack. 😄

**Comment by StewartJingga** [comment]
This is my proposed models for our emitter interface

```
type Record struct {
	// there will be getter and setter for this
	data interface{}
}

type ListenerCallback func(batch []Record) error
type Middleware func(src Record) (res Record, err error)

type Emitter interface {
	// SetListener will register callback with a batch size to the emitter
	// Calling this will not start listening yet, use Listen() to start listening
	SetListener(callback ListenerCallback, batchSize int) *Emitter

	// Listen will start listening to emitter for any pushed records
	// This process is blocking until the emitter is closed
	// and all listeners have received all the emitted records
	Listen() error

	// Emit will run the record through all the registered middleware
	// and emit the record to all registerd listeners
	Emit(Record) error

	// SetMiddleware registers a middleware that will be used to
	// process given record before emitting
	SetMiddleware(m Middleware) *Emitter

	// Close the emitter and signalling all listeners of the event
	Close()
}
```

Sample usage
```
emitter := NewEmitter().
		SetListener(Sink, 2).
		SetListener(Sink, 3).
		SetMiddleware(Processor).
		SetMiddleware(Processor)

// we run this in goroutine because emitter.Listen() which is called on next line will block
// basically we need a thread to listen and another thread to emit data (extractor)
go func() {
	// extractor plugin will run this
	sampleData := []int{1, 2, 3, 4, 5}
	for _, d := range sampleData {
		err = emitter.Emit(Record{
			data: d,
		})
		if err != nil {
			return
		}
	}

	// close the emitter signalling that the extractor is done emitting records
	emitter.Close()
}()

// this process is blocking
err := emitter.Listen()
if err != nil {
	panic(err)
}

// this will be called when emitter is closed
// and all listeners have processed the emitted records
fmt.Println("DONE!")
```

wdyt? @ravisuhag @kushsharma
