### ISSUE TITLE
Provide descriptive debugging info on lint

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#197]
**Is your feature request related to a problem? Please describe.**
Running lint on meteor recipes does not provide which line in the recipe has an issue. 

**Describe the solution you'd like**
Lint command should provide more descriptive error messages. Message should provide a file name, line number, and proper error message. As an example
```
recipes/sample.yaml:44:10:invalid config hostname for Columbus sink.
```

**Comment by scortier** [comment]
@ravisuhag 
Generally , `runtime.Caller(depth)` method is used to display the line and file name, but while looking the stackTrace on panic, the error is not referring to yaml file, the trace was only visible till `cmd/lint.go`. I am wondering then how can we provide file name and line number particularly in yaml . Looking over other approaches as well.

If you have any approach for it , let me know

**Comment by ravisuhag** [comment]
@scortier Check this thread. 
https://github.com/go-yaml/yaml/issues/108
