### ISSUE TITLE
refactor: fix golint issues

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#205]
There are some golint issues present all across the codebase. The goal with this issue is to fix all known issues as suggested in go report card as well. 

https://goreportcard.com/report/github.com/odpf/meteor

**Comment by kushsharma** [comment]
We can use golangci same as what we have in optimus right?

**Comment by scortier** [comment]
> We can use golangci same as what we have in optimus right?

Yes , we can use it , the difference between `golint` and `golangci-lint` is:
- `golint` majorly focuses on the comments for each functions and variable naming
- `golangci-lint` majorly checks for critical `errcheck` and extra newline.

**Comment by kushsharma** [comment]
I think `golangci-lint` supports more than 30 linters. It does a lot more.

**Comment by scortier** [comment]
> I think `golangci-lint` supports more than 30 linters. It does a lot more.

Yes, but I manually checked from both and found completely different linting error in both.

**Comment by kushsharma** [comment]
Yeah yeah, so what I mean is we can use `golint` with golangci as one of the [linter](https://golangci-lint.run/usage/linters/#golint).  The reason you are seeing the different results is because of how you might have configured the golangci linter.

**Comment by kushsharma** [comment]
Once we have a standard golangci linter, I think we can use it across all odpf products as well.

**Comment by kushsharma** [comment]
@ravisuhag do we really need to fix these golint errors btw? I mean general errors are fine but this specific warning of comments over every function is very annoying I think. I have disabled this for optimus at the moment 😄

**Comment by ravisuhag** [comment]
@kushsharma I think these comments add a lot of value during development when added properly anytime that function is used. IMO, we should proper description of all exposed methods.
