### ISSUE TITLE
Allow interactive selection of source and sinks in new

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#226]
**Is your feature request related to a problem? Please describe.**
Meteor gen command right now expects the name of plugins as flags.

**Describe the solution you'd like**
Meteor can be extended to Interactively ask for names of plugins from the available list of plugins to generate recipes.

**Comment by ishanarya0** [comment]
@ravisuhag we have to keep the non-interactive mode as well, right? if yes, shall we keep a boolean flag to enable interactive mode?

**Comment by ravisuhag** [comment]
> 

Yes.
