### ISSUE TITLE
Support meteor.var or .env for secrets

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#228]
Instead of meteor_prefix variable accept a .var or .env for accepting secrets. or maybe support both. If not provided, meteor should also promote users for secrets in the command line before running.

**Comment by burntcarrot** [comment]
However, [template](https://pkg.go.dev/text/template) is being used in the recipe reader for applying the parsed template to `reader.data`:

https://github.com/odpf/meteor/blob/09db3663770352943a17e79235ca6d8f0a1532fd/recipe/reader.go#L54

**Comment by ravisuhag** [comment]
@burntcarrot Salt does not have a package to serve this need at the moment.

**Comment by StewartJingga** [comment]
>So, I don't think changing the method signature for populateData() would be possible, as template execution is dependent upon the reader's data.

@burntcarrot  There are two parts when reading recipe from .yaml to memory (recipe struct):
1. collecting data (right it is only via `meteor_prefix`
2. and applying the data to the recipe

This proposed feature/enhancement will only focus on part 1 which is collecting data. At this stage it is totally easy to extend.
