### ISSUE TITLE
Log extracted record information

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#230]
**Is your feature request related to a problem? Please describe.**
Meteor run does not mention during extraction which records it has extracted. 

**Describe the solution you'd like**
Meteor run can log the name of the record it succeeds to extract. 
```
Successfully extracted table `user_table` from data source `xyz` with recipe `recipe_name`
Successfully extracted dashboard `total users` from data source `redash` with recipe `recipe_name`

**Comment by GrayFlash** [comment]
@ravisuhag for an extractor we will extract metadata for all the tables and dashboards that are available in the given host, will it be feasible to log names of all these??
For e.g. even for test in `postgres` we create 2 tables `applicant` and `jobs`, so the output will be like

```
Successfully extracted table `applicant`, and `jobs` from data source `postgres` with recipe `sample1`
```

This is just for 2 tables and we might move on to have 1000's of tables in some data sources, so will logging all of them be a good thing??

**Comment by GrayFlash** [comment]
But I think if we can allow user to narrow down to the name of database while he passes config, he and then add these logging record names, should be a great option. wdyt??

**Comment by StewartJingga** [comment]
@ravisuhag I have 2 questions regarding this:

1. do you want the log to be like a sentence like you proposed? our current log has a key value like information which we can use like, `type=extractor table=sample-urn plugin=postgres recipe=sample1`

2. When you say successfully extracted, is exactly after extracting from source and before processing or after successfully sinking?

**Comment by scortier** [comment]
@ravisuhag @StewartJingga @mabdh with which approach are we proceeding with this issue ?

Suggested approach : 
We can add a utility function in all the extractors which will append all the tables in a string array and its count and it will be used to log detail in a key-value format  like `tables = table1, table2  table_count=2`.
wdyt ??

**Comment by ravisuhag** [comment]
@scortier @StewartJingga I am thinking instead of putting this in extractors, it can be handled at central place from agent. Yes, something like this will work 
`type=extractor table=sample-urn plugin=postgres recipe=sample1`
Doing is just after extraction will be better. We can log one line for sink also if needed which shows that this info has been successfully sent to sink as well. But both the abstractions should ideally be handled by agent only.

**Comment by StewartJingga** [comment]
@scortier  Yes it would be better to be centralised on the Agent itself, at least the basic information.
If we want to log in the extractor, it is totally up to the extractor itself, but it would not be required unless it has information that is generic to that extractor only.
