### ISSUE TITLE
refactor(columbus): update api of columbus sink to v1beta1

### ISSUE THREAD

**Issue by mabdh** [odpf/meteor#296]
**Is your feature request related to a problem? Please describe.**
Columbus is updating the version API from `v1` to `v1beta1` [ref](https://github.com/odpf/columbus/issues/57), we need to update meteor columbus sink API to sync with the columbus changes.

**Describe the solution you'd like**
<del>Instead of hardcoding the version to `v1beta1`, perhaps better for us to make the version configurable via config.</del>
We hardcode the update of version `v1` to `v1beta` in columbus sink.

**Comment by mabdh** [comment]
wdyt @ravisuhag @StewartJingga  ?

**Comment by StewartJingga** [comment]
I have nothing against it, but I still think it is still okay to hardcode the version because most times, if api version changes, usually what causes it are changes in API contract, and we might need to update the code anyway to follow the new contract.

**Comment by mabdh** [comment]
> I have nothing against it, but I still think it is still okay to hardcode the version because most times, if api version changes, usually what causes it are changes in API contract, and we might need to update the code anyway to follow the new contract.

hmm yeah, that makes sense. let's use hardcoded version for this.
