### ISSUE TITLE
feat(metabase): use alias for urn generation instead of using instance's host

### ISSUE THREAD

**Issue by StewartJingga** [odpf/meteor#352]
**Is your feature request related to a problem? Please describe.**
Metabase extractor is using `host` from config as part of URN component.
```
# recipe.yaml
source:
  name: metabase
  config:
    host: https://my-metabase.com

# json output
{
  "resource": {
    "urn": "metabase::https://my-metabase.com/dashboard/120"
  }
}
```

This raised an issue because when I am changing my host to another dns, it will generate a different `urn` which will be treated as another new metadata in my system.

**Describe the solution you'd like**
Metabase extractor should not using host as its urn and allow adding label or alias from config instead.
```
# recipe.yaml
source:
  name: metabase
  config:
    host: https://my-metabase.com
    instance_label: my-metabase

# json output
{
  "resource": {
    "urn": "metabase::my-metabase.com/dashboard/120"
  }
}
```

**Comment by GrayFlash** [comment]
@StewartJingga the problem seems clear, though I had one doubt around how users are deciding this `instance-label` they need to pass to the config. I mean is there a pattern they should follow or something??

**Comment by StewartJingga** [comment]
no pattern atm, it will be left for users to decide how they want to label their metadata. wdyt?
