### ISSUE TITLE
feat: add `auth_token` to tableau extractor

### ISSUE THREAD

**Issue by GrayFlash** [odpf/meteor#358]
**Is your feature request related to a problem? Please describe.**
We use `sessionID` for setting up client in metabase, so similary we can use `auth token` for the purpose on the tableau.

**Describe the solution you'd like**
Add `auth token` to the config for tableau, and make username and password optional. Similar to #351

**Comment by StewartJingga** [comment]
Both `auth token` and `username/password` are optional but either one of them has to be provided.
