### ISSUE TITLE
file sink overwrites rather than append

### ISSUE THREAD

**Issue by bsushmith** [odpf/meteor#366]
**Describe the bug**
File sink overwrites the file rather than appending records to it. 

Example: `optimus` extractor emits record for every job, and if `file` sink plugin is used. At the end of recipe run, the file will contain only one job record(the last one), rather than all the jobs. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a sample file sink recipe. eg: using optimus as extractor and file as sink
2. run the recipe
3. check the records in the file.

**Expected behaviour**
The file should contain all records in the `file` sink.

**Comment by GrayFlash** [comment]
Hey, @bsushmith thanks for catching the error and raising the bug, and picking it up. Just had one query, so suppose an output file containing the records from the previous run already exists, and the user runs it again, what should happen in this case. Cause of I append it to the same output file it will have a lot of redundant data.

**Comment by StewartJingga** [comment]
> Hey, @bsushmith thanks for catching the error and raising the bug, I'm picking it up. Just had one query, so suppose an output file containing the records from the previous run already exists, and the user runs it again, what should happen in this case. Cause of I append it to the same output file it will have a lot of redundant data.

In that case, we can make it configurable. User can decide to make it as a replace or append. Default would be replace I'd think 🤔 . wdyt @bsushmith ?

**Comment by bsushmith** [comment]
replace by default and user configurable. 👍 @StewartJingga
