### ISSUE TITLE
bug: config not found message on all commands that do not require it

### ISSUE THREAD

**Issue by StewartJingga** [odpf/meteor#394]
**Describe the bug**
I keep getting below message when running all meteor commands that does not require config file
```
unable to find config file, loading from env and defaults: open ./meteor.yaml: no such file or directory
```

**To Reproduce**
1. Make sure you don't have `meteor.yaml`
2. Run `meteor list extractors`
3. See message

**Expected behavior**
Should not show `unable to find config file` message for below commands that do not require it:
1. meteor list
2. meteor info
3. meteor gen
4. others...

**Comment by sudo-suhas** [comment]
Is there any value in instrumentation for linting recipes?

**Comment by StewartJingga** [comment]
> Is there any value in instrumentation for linting recipes?
> 
> context: We configure the monitoring agent using the options in the configuration file. So trying to understand if instrumentation itself can be removed for `lint` command so that it can run without needing to load configuration.

@sudo-suhas  It should be removable as we only need it when running the recipe.
