### ISSUE TITLE
Simplify meteor models

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#397]
**Is your feature request related to a problem? Please describe.**
The level of nesting in meteor models is a lot. Where multiple models are nested within each other. which makes it hard for extractor to serialise their data. Also, current models are in different lines compared to compass. 

**Describe the solution you'd like**
We can simplify models into a more simplified approach. where asset is one models which can have table, topic and other models as one of its type.

**Comment by StewartJingga** [comment]
@bsushmith fyi

We are using `odpf/proton` Asset model which just got updated recently in these two PRs respectively.

https://github.com/odpf/proton/pull/161

- move from having multiple models (Table, Dashboard, etc) to one main Asset model that wrap the model (Table, Dashboard, etc) inside `Data` field.
- All common fields across models is moved to `Asset` model.

https://github.com/odpf/proton/pull/174

- Move Asset.Attributes to Asset.Data.Attributes
