### ISSUE TITLE
proto: invalid type: map[string]string for bigquery recipe when include_column_profile is false

### ISSUE THREAD

**Issue by anjali9791** [odpf/meteor#410]
Run a big query to console recipe with include_column_profile as false. It fails when creating the Table struct with the issue proto: invalid type: map[string]string
I suspect the issue is because labels have been removed from the Table proto. It fails when it tries to convert lables of type map[string]string to map[string]interface. Earlier it was part of Properties and not Attributes.
Code for reference: https://github.com/odpf/meteor/blob/0aba47c054dc1305bdce5e1ec58607d7a2222d72/plugins/extractors/bigquery/bigquery.go#L223

**Comment by StewartJingga** [comment]
@anjali9791 created a PR for the fix https://github.com/odpf/meteor/pull/411

thanks for reporting and sorry for the inconvenience 🙏
