### ISSUE TITLE
use base64 encoded instead of service account string directly in bigquery extractor

### ISSUE THREAD

**Issue by bsushmith** [odpf/meteor#424]
**Is your feature request related to a problem? Please describe.**
We use terraform to deploy meteor for the bigquery extractor. bigquery extractor takes in the service account credentials directly as a JSON in its [config](https://github.com/odpf/meteor/tree/main/plugins/extractors/bigquery#usage). While trying to use meteor's templating feature for fetching values from env and injecting to the recipe - we have issues with meteor parsing with this JSON. It has become a non-trivial problem to resolve this.

**Describe the solution you'd like**
Instead of passing service-account JSON, let meteor bigquery extractor take in a simple base64 encoded service account string, and let it decode in the code.

**Comment by StewartJingga** [comment]
to avoid breaking changes, we can do:
1. new `service_account_base64: string` config that will be take precedence over `service_account_json`
2. have a new config `credential_type: string` which could be `base64` or `json`.

personally I like the first approach better, wdyt @bsushmith ?
